version: '3.4'

services:
  admin.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  auth.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

